import { Inter } from 'next/font/google'
import './globals.css'
import NavberPage from './navber/page'
import FooterPage from './footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <NavberPage></NavberPage>
        </nav>
        {children}
        <FooterPage></FooterPage>
        </body>
    </html>
  )
}
